### ISSUE TITLE
Remove global incremental ids for networks, channels, users and messages

### ISSUE THREAD

**Issue by xPaw** [thelounge/thelounge#2341]
We're unnecessarily "leaking" how many users use a particular instance by keeping global counts of all the objects. For example, connect to our demo and you'll see `#chan-1300` in the URL.

- [x] Networks: I think we can just straight up remove ids and use guids that were recently added. #2390
- [x] Clients: I haven't looked very closely, but I think ids here are only used for `socket.join` so we can just as easily use guids here if necessary. #2344
- [x] Channels: keep a local id per client #2396
- [x] Messages: Keep a local counter per client as there's some logic that relies on incremental ids (like loading more messages). #2396

**Comment by McInkay** [comment]
Sounds good, network ids can definitely be removed, we can used the guids for everything.

The others sound sensible on the surface, I've not looked too much into them though.
