### ISSUE TITLE
Vue branch tracking issue

### ISSUE THREAD

**Issue by xPaw** [thelounge/thelounge#2636]
- [x] Unread marker needs more tweaking and fixing
- [x] Port ban list
- [x] Port channel list
- [x] Port ignore list
- [x] Port keybinds in user list (thanks @richrd)
- [x] Trim channel when switching away from it
- [x] "Show more" button needs some logic
- [x] More history may not always load
- [x] Previews need to be ported
- [x] Previews should wait for media to load before rendering
- [x] Previews should keep scroll to bottom
- [x] Add preview toggle arrow next to links
- [x] Make sure client reconnections work correctly
- [x] Joining a channel may duplicate a message (topic or join)
- [x] Completing nicks with tab sends wrong message (doesn't update model)
- [x] Remove version of `parse` that generates raw HTML
- [x] Link previews don't work in `/me` actions
- [x] Loading more history doesn't retain scroll properly
- [x] Entire collapse line is clickable, not just the info text
- [x] Menu swipe doesn't work on mobile
- [x] Tapping a channel instantly shows ghost border
- [x] Holding finger on channel no longer opens context menu
- [x] Port input resizing when typing
- [x] Keep scroll to bottom when resizing window (opening virtual keyboard)
- [x] Shift+Enter should insert a new line
- [x] Video previews may break scrolltobottom

**Comment by xPaw** [comment]
Tracked in PR #2647 now.
