### ISSUE TITLE
Vue port/rewrite tracking issue

### ISSUE THREAD

**Issue by xPaw** [thelounge/thelounge#2964]
A lot of work has been done in #2647 to move the state, channel list and the chat window itself into Vue, but there's other components that currently still remain in jQuery and are not yet ported.

Because Vue porting takes a substantial amount of work, as it touches majority of the client code, merging other PRs that touch client code which is not yet ported to Vue is unwanted as that duplicates the effort.

This is the list so far, with probably more things that are missing:
- [x] Channel list (sidebar)
- [x] Chat window along with all the messages and previews
- [x] User lists in chats
- [x] Settings page
- [x] Version checker page
- [x] Changelog page
- [x] Connect/edit network page
- [x] Help page
- [x] Sign in page
- [x] Slideout code
- [x] Image viewer
- [x] jQuery code that handles viewport clicks and other stuff
- [x] Vue routing
- [x] Sign in form flashes on page load (if auth token exists)
- [x] Binding `$refs.element.close` in channelwrapper is a bad idea and breaks (collapsed channels, no element ref)
- [x] scrolling up may not load more history?
- [x] Footer buttons should have `active` class added
- [x] Pressing back button which goes to window does not reset activeChannel
- [x] Network edit still references handlebars template
- [x] Context menu 'remove' on networks does not work
- [x] Use `findChannel` instead of manually looping through channels
- [x] Convert remaining `vueApp` variables to vuex state
- [x] Emoji auto complete arrow up/down keys switch message history, not just selected option
- [x] Pressing browser back button in image viewer should close it (router)
- [x] Remove `Vue.filter` (if possible)
- [x] Remove `renderPreview.js`
- [x] Remove `window.vueMounted` and `lounge.js`
- [x] Opening changelog and reloading the page does not load it
- [x] Opening settings and reloading the page breaks
- [x] Opening connect and reloading the page breaks
- [x] Handle initial route on page load if there's none correctly
- [x] Better handle invalid routes
- [x] `#/sign-in` can still be opened if logged in
- [x] Open first channel instead of connect window on first load after server restart
- [x] Bug: NavigationDuplicated "Navigating to current location ("/chan-17") is not allowed"
- [x] Fix `require` that are within functions, due to circular dependencies
- [x] Cleanup settings/options/webpush
- [x] Remove `utils.js`
- [x] Context menus
- [x] Autocompletion (textcomplete menus)
- [x] Replace all `require` with `import` in client code for tree shaking
- [x] Close image viewer with ESC key
- [x] Closing context menu doesn't seem to refocus previously active element
- [x] Change `:focus/:hover` to `.active` in context menus (like in user list, to prevent keyboard/mouse focused element getting out of sync)
- [x] Use mousetrap for escape keybinds in contextmenu/imageviewer (and make sure its unbound if its bound in mounted event)
- [x] Client sometimes fails to reconnect with message `Waiting to reconnect... (Transport Error)`
- [x] Fix `force sync` button and warnings
- [x] Move `upload-overlay` to vue
- [x] Convert keybinds to use state instead of jquery
- [x] `parse.js` generates context menus on channels for currentChannel which is not exactly right (and that breaks tests)
- [x] Clicking a mentioned nick in chat does not open the context menu
- [ ] Check up on vue router urls to keep backwards compatibility
- [ ] Final, nice to have, refactor: Getting rid of `getElementById` and `querySelector` and instead referencing elements via Vue.

Majority of the work revolves around porting individual pages, which should allow us to finally rewrite the damn window handling (which is currently handled rather poorly, and is hacky with image viewer).

When the remaining items are ported, we should be able to completely remove the following dependencies completely out of the project:
- [x] jquery
- [x] jquery-ui
- [x] handlebars
- [x] handlebars-loader
- [x] html-minifier
- [x] html-minifier-loader
- [x] css.escape

**Comment by c-ciobanu** [comment]
By window handling what do you exactly mean?

**Comment by xPaw** [comment]
The code that switches between chat views and other 'pages'.

**Comment by c-ciobanu** [comment]
That's the routing, it's fairly easy with vue.
I can help with that.

**Comment by xPaw** [comment]
Pretty much, I'm not sure we would want to use a full blown router though.

**Comment by c-ciobanu** [comment]
Why not?

**Comment by xPaw** [comment]
We have things like image viewer on top, but it still affects history. That might be a little painful to do with vue router.

I'd say the initial implementation should be simple with switching components (kind of like chat channels are currently implemented), and then we can try swapping all of that with a real router (for pages/windows and channels).

**Comment by c-ciobanu** [comment]
What's the logic behind the image viewer? it can be visited from every page and can change the history? If this is the case i think it can be done with the router but it's not so straightforward.

From experience i would say that using the router is much easier than switching components through props or whatever.
I think that adding to the project Vue Router and vuex will simplify it a lot, a lot of things can be saved in the store from what I've seen, this will reduce the amount of props passed down.

**Comment by Daniel15** [comment]
Out of curiosity, is there any particular reason for choosing Vue rather than React? Is there a discussion for that somewhere?

**Comment by MiniDigger** [comment]
another major benefit is that the rewrite can be done on the fly, not all components need to use vue. I don't think this is easily possible with react.

**Comment by Daniel15** [comment]
@MiniDigger You can definitely convert to React one piece at a time. You just need to call `ReactDOM.render` in the appropriate place. That's pretty common at Facebook - in fact, news feed is mostly server-rendered, but the likes/comments are rendered with React. A large app I used to work out (~350,000 lines of JS) was converted from a legacy JS framework to React over 2 years, one piece at a time. 

Anyways, Vue is good too. You can't go wrong with either framework. :)

**Comment by MaxLeiter** [comment]
@Daniel15 fwiw there have been two attempts to move The Lounge to react:

https://github.com/thelounge/thelounge/pull/633
https://github.com/thelounge/thelounge/pull/610

**Comment by Daniel15** [comment]
> while you're around, do you know if there is the slightest chance Facebook Open Source could very generously help us at opencollective.com/thelounge ? 😁

@astorije - I don't think Facebook would sponsor a project that the company isn't using and that doesn't use any Facebook technologies, particularly since it basically competes with Messenger since you could consider both things to be communication platforms. Sorry 😛

**Comment by astorije** [comment]
> @astorije - I don't think Facebook would sponsor a project that the company isn't using and that doesn't use any Facebook technologies

@Daniel15, I mean, FB has sponsored Vue and Material UI, so one can dream :D Still, it would be slick if FB could spare some change for us, if somehow it comes up in a conversation you're involved in... 🙏
(Yes, I will mark this comment as off-topic 😅)

**Comment by xPaw** [comment]
We're getting close to being done, we would appreciate if people switched to the `vue` branch and gave it some testing.
